### ISSUE TITLE
Add support for linux/arm64

### ISSUE THREAD

**Issue by olmohake** [hasura/ndc-stripe#10]
Hi @hgiasac, I was very exited to see this connector is part of the official connector hub now :)
I just wanted to give it a try but sadly couldn't get it running on my system as there's no docker image for linux/arm64.

**Comment by hgiasac** [comment]
Hi @olmohake

Sure. I'll release the new version with linux/arm64 support soon.

**Comment by hgiasac** [comment]
@olmohake FYI the docker image for `linux/arm64` was released in v0.3.0.
