### ISSUE TITLE
Introspection not working

### ISSUE THREAD

**Issue by olmohake** [hasura/ndc-stripe#13]
Set up the connector according to hasura ddn documentation.
Once i run ```ddn connector introspect stripe``` the docker container starts and the service is responding as expected on all endpoints, including a proper schema response and a void message with status 200 on /health.  But the ddn cli is freezing with a *Waiting for the Connector service to be healthy...* message.

Any idea why?

**Comment by hgiasac** [comment]
It works on my side. I don't have an arm64 machine to help you verify.
However, IIUC the CLI listens to the `<subgraph>_<connector>_WRITE_URL=http://local.hasura.dev:xxx` endpoint env variable in the `.env` file. You can check if the URL is reachable on the host network. If not there would be a network or CLI config issue.

**Comment by olmohake** [comment]
Just realised i am facing the same problem with any connector. Sorry for not checking before. It was working the last time i was using the postgres connector, but that has been a while ago. Most likely related to updates in the ddn cli. Will open general issue.
