### ISSUE TITLE
How can I use this connector in my supergraph?

### ISSUE THREAD

**Issue by itai-spiritt** [hasura/ndc-stripe#7]
I have a DDN running with PostgreSQL connector.
How can I integrate this connector into my supergraph?

**Comment by hgiasac** [comment]
Hey @itai-spiritt 
The Stripe connector hasn't been published yet. We will publish it soon

**Comment by hgiasac** [comment]
Stripe connector was released to the DDN. You can search `hasura/stripe` when initializing the connector via `ddn connector init -i`

**Comment by itai-spiritt** [comment]
Great thanks, I'll try it

What are the steps to produce a NDC for other openAPI services, such as
hubspot?

**Comment by hgiasac** [comment]
@itai-spiritt you can use OpenAPI connector. Let's check out the guide docs
https://hasura.io/docs/3.0/getting-started/build/connect-to-data/connect-a-source?db=OpenAPI
